project:
  type: website
  output-dir: docs

website:
  title: "Data by Derek"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Projects"
        href: projects.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

resources:
  - projects/vancouvertrees